<div class="small-12 medium-8 large-12 columns">
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Listado de Usuarios</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <a href="<?php echo $this->url('create-users'); ?>" class="button tiny radius">Crear Usuario</a>
                    <div class="panel">
                        <form action="<?php echo $this->url('delete-users'); ?>" method="post">
                            <table class="large-12">
                                <thead>
                                    <tr>
                                        <th>&nbsp;</th>
                                        <th>Cliente</th>
                                        <th>Nombre y Apellido</th>
                                        <th>Email</th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->users as $user) { ?>
                                    <tr>
                                        <td><input type="checkbox" name="cluiId[]" value="<?php echo $user->getCluiId(); ?>"></td>
                                        <td><?php echo $user->getClii()->getClivName(); ?></td>
                                        <td>
                                            <?php echo $user->getCluvName() . " " . $user->getCluvLastname(); ?>
                                        </td>
                                        <td><?php echo $user->getCluvEmail(); ?></td>
                                        <td>
                                            <a href="<?php echo $this->url('create-users', array('id' => $user->getCluiId())); ?>"
                                               class="button tiny radius">Editar</a>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                            <input type="submit" name="deleteuser" value="Borrar Usuarios" class="button warning tiny radius">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="small-12 medium-4 large-5 columns">
   &nbsp;
</div>
