<div class="small-12 columns">
    <div class="row">
        <ul class="breadcrumbs">
            <li><a href="<?php echo $this->url('my-repo'); ?>">Home</a></li>
            <li class="current"><a href="#">Carpeta 1</a></li>
        </ul>
    </div>
    <div class="row">
        <div class="small-6 medium-2 columns">
            <a href="#" class="button radius tiny expand" data-reveal-id="createFolderModal">Crear Carpeta</a>
            <div id="createFolderModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>Creará un carpeta nueva dentro de <strong><em>carpeta 1</em></strong></p>
                <div class="small-12 columns">
                    <label>Nombre de la nueva carpeta
                        <input type="text" placeholder="escriba un nombre para la nueva carpeta" />
                    </label>
                    <button class="button tiny">Crear</button>
                </div>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
        <div class="small-6 medium-10 columns">
            <a href="#" class="button radius tiny" data-reveal-id="uploadFileModal">+ Subir Archivos</a>
            <div id="uploadFileModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>Subirá archivos dentro de <em>carpeta 1</em></p>
                <div class="small-12 columns">
                    <label>Archivo
                        <input type="file" />
                    </label>
                    <label>Descripción del Archivo
                        <textarea placeholder="Escriba una descrición del archivo que subirá"></textarea>
                    </label>
                    <button class="button tiny">Subir</button>
                </div>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns text-right">
            <a href="#" data-reveal-id="deleteFolderModal">Borrar Carpetas</a>
            <div id="deleteFolderModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>Al borrar las carpetas seleccionadas, se borrarán todo el contenido que tenga y no podrá recuperarse. ¿Está seguro de continuar?</p>
                    <button class="button tiny alert">Borrar</button>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
        <form>
            <div class="small-12 columns">
                <div class="panel">
                    <?php for($i=1; $i<=rand(1,5); $i++) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-1', 'row-2'))->next() ?>">
                        <div class="small-12 columns">
                            <input id="archivo-1" type="checkbox"><label for="archivo-1"><a href="#">Carpeta 1</a></label>
                        </div>
                        <div class="small-12 columns tab-40 text-small">
                            <?php echo rand(1,8); ?> Carpetas, <?php echo rand(0,20); ?> Archivos
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </form>
        <div class="small-12 columns text-right">
            <a href="#" data-reveal-id="deleteFilesModal">Borrar Archivos</a>
            <div id="deleteFilesModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>¿Está seguro de borrar los archivos seleccionados?</p>
                    <button class="button tiny alert">Borrar</button>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
        <form>
            <div class="small-12 columns">
                <div class="panel">
                    <?php for($i=1; $i<=rand(2,20); $i++) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-2', 'row-1'))->next() ?>">
                        <div class="small-8 large-5 columns">
                            <input id="archivo-1" type="checkbox">
                            <label for="archivo-1"><a href="<?php echo $this->url('view-file'); ?>">Archivo <?php echo $i; ?></a></label>
                        </div>
                        <div class="show-for-large-up large-5 columns">Mauris varius, ex sit amet pretium viverra...</div>
                        <div class="small-4 large-2 columns text-right"><a href="#">Descargar</a></div>
                        <div class="small-4 medium-2 large-2 columns text-small tab-40">13-02-2015</div>
                        <div class="small-8 medium-2 large-2 columns text-small">Descargas: <?php echo rand(1, 9); ?></div>
                        <div class="small-12 medium-8 columns text-small show-for-medium-up" ><?php echo md5(rand(1, 9)); ?></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </form>
    </div>
</div>