<div class="small-12 columns">
    <div class="row">
        <ul class="breadcrumbs">
            <li><a href="<?php echo $this->url('my-repo'); ?>">Home</a></li>
            <?php
            $breadcrumb = $this->bc;
            $last = array_pop($breadcrumb);
            foreach($breadcrumb as $bc) {
            ?>
            <li><a href="<?php echo $this->url('my-repo', array('folder'=>$bc['fsciId'])); ?>"><?php echo $bc['fscvRealName']; ?></a></li>
            <?php } ?>
            <li class="current"><a href="<?php echo $this->url('my-repo', array('folder'=>$last['fsciId'])); ?>"><?php echo $last['fscvRealName']; ?></a></li>
        </ul>
    </div>
    <div class="row">
        <div class="small-6 medium-2 columns">
            <a href="#" class="button radius tiny expand" data-reveal-id="createFolderModal">Crear Carpeta</a>
            <div id="createFolderModal" class="reveal-modal tiny" data-reveal>
                <br />
                <form action="<?php echo $this->url('create-folder'); ?>" method="post">
                    <input type="hidden" name="folder" value="<?php echo $this->folder; ?>">
                    <p>Creará un carpeta nueva dentro de <strong><em>carpeta 1</em></strong></p>
                    <div class="small-12 columns">
                        <label>Nombre de la nueva carpeta
                            <input type="text" name="folder_name" placeholder="escriba un nombre para la nueva carpeta" />
                        </label>
                        <button class="button tiny" type="submit">Crear</button>
                    </div>
                    <a class="close-reveal-modal">&#215;</a>
                </form>
            </div>
        </div>
        <div class="small-6 medium-10 columns">
            <a href="#" class="button radius tiny" data-reveal-id="uploadFileModal">+ Subir Archivos</a>
            <div id="uploadFileModal" class="reveal-modal tiny" data-reveal>
                <br />
                <form action="<?php echo $this->url('add-file'); ?>" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="folder" value="<?php echo $this->folder; ?>">
                    <p>Subirá archivos dentro de <em>carpeta 1</em></p>
                    <div class="small-12 columns">
                        <label>Archivo
                            <input type="file" name="file" />
                        </label>
                        <label>Descripción del Archivo
                            <textarea placeholder="Escriba una descrición del archivo que subirá" name="file_description"></textarea>
                        </label>
                        <button class="button tiny" type="submit">Subir</button>
                    </div>
                    <a class="close-reveal-modal">&#215;</a>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns text-right">
            <a href="#" data-reveal-id="deleteFolderModal">Borrar Carpetas</a>
            <div id="deleteFolderModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>Al borrar las carpetas seleccionadas, se borrarán todo el contenido que tenga y no podrá recuperarse. ¿Está seguro de continuar?</p>
                    <button class="button tiny alert">Borrar</button>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
        <form>
            <div class="small-12 columns">
                <div class="panel">
                    <?php foreach($folders as $folder) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-1', 'row-2'))->next() ?>">
                        <div class="small-12 columns">
                            <input id="folder_<?php echo $folder['fsciId']; ?>" type="checkbox"><label for="folder_<?php echo $folder['fsciId']; ?>"><a href="<?php echo $this->url('my-repo', array('folder'=>$folder['fsciId'])); ?>"><?php echo $folder['fscvRealName']; ?></a></label>
                        </div>
                        <div class="small-12 columns tab-40 text-small">
                            <?php echo rand(1,8); ?> Carpetas, <?php echo rand(0,20); ?> Archivos
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </form>
        <div class="small-12 columns text-right">
            <a href="#" data-reveal-id="deleteFilesModal">Borrar Archivos</a>
            <div id="deleteFilesModal" class="reveal-modal tiny" data-reveal>
                <br />
                <p>¿Está seguro de borrar los archivos seleccionados?</p>
                    <button class="button tiny alert">Borrar</button>
                <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
        <form>
            <div class="small-12 columns">
                <div class="panel">
                    <?php foreach($files as $file) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-2', 'row-1'))->next() ?>">
                        <div class="small-8 large-5 columns">
                            <input id="file-<?php echo $file['fsciId']; ?>" type="checkbox">
                            <label for="file-<?php echo $file['fsciId']; ?>"><a href="<?php echo $this->url('view-file', array('filename'=>$file['fisvName'])); ?>"><?php echo $file['fscvRealName']; ?></a></label>
                        </div>
                        <div class="show-for-large-up large-5 columns"><?php echo $file['fsctDescription']; ?></div>
                        <div class="small-4 large-2 columns text-right"><a href="<?php echo $this->url('download-file', array('filename'=>$file['fisvName'])); ?>">Descargar</a></div>
                        <div class="small-4 medium-2 large-2 columns text-small tab-40"><?php echo $file['fscdUploadDate']->format('d-m-Y'); ?></div>
                        <div class="small-8 medium-2 large-2 columns text-small">Descargas: <?php echo rand(1, 9); ?></div>
                        <div class="small-12 medium-8 columns text-small show-for-medium-up" >md5-hash: <?php echo $file['fisvName']; ?></div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </form>
    </div>
</div>
