<div class="small-12 columns">
    <div class="row">
        <ul class="breadcrumbs">
            <li><a href="<?php echo $this->url('my-repo'); ?>">Home</a></li>
            <li class="current"><a href="#">Carpeta 1</a></li>
        </ul>
        </div>
    <div class="row">
        <div class="small-12 medium-6 columns">
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel">
                    <div class="row">
                        <div class="small-12 columns strong">
                        <strong>Nombre del Archivo</strong>
                        </div>
                        <div class="small-12 columns">
                        <?php echo $file['real_name']; ?>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="small-12 columns">
                            <a href="<?php echo $this->url('download-file', array('filename'=>$file['name'])); ?>">Descargar</a>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="small-12 columns">
                            <strong>Tamaño del Archivo</strong>
                        </div>
                        <div class="small-12 columns">
                            <?php echo $file['size']; ?>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="small-12 columns">
                            <strong>Fecha de Subida</strong>
                        </div>
                        <div class="small-12 columns">
                            <?php echo $file['upload_date']; ?>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="small-12 columns">
                            <strong>Descripción del Archivo</strong>
                        </div>
                        <div class="small-12 columns">
                            <?php echo $file['description']; ?>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="small-12 medium-6 columns text-right">
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel">
                        <div class="row text-center show-for-medium-up">
                            <img alt="" src="/img/xls-300x300.png">
                        </div>
                        <button class="button tiny alert" data-reveal-id="deleteFileModal">Borrar</button>
                        <div id="deleteFileModal" class="reveal-modal tiny" data-reveal>
                            <br />
                            <p>¿Está seguro de borrar este archivo?</p>
                            <button class="button tiny alert">Borrar</button>
                            <a class="close-reveal-modal">&#215;</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>