<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FileSystem extends \Application\Entity\FileSystem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiId', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiParentId', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiType', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvName', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvRealName', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvMimetype', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvExtension', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fistDescription', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisdUploadDate', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvUploadIp', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvStatus');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiId', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiParentId', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisiType', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvName', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvRealName', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvMimetype', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvExtension', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fistDescription', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisdUploadDate', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvUploadIp', '' . "\0" . 'Application\\Entity\\FileSystem' . "\0" . 'fisvStatus');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FileSystem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFisiId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getFisiId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisiId', array());

        return parent::getFisiId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisiParentId($fisiParentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisiParentId', array($fisiParentId));

        return parent::setFisiParentId($fisiParentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisiParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisiParentId', array());

        return parent::getFisiParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisiType($fisiType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisiType', array($fisiType));

        return parent::setFisiType($fisiType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisiType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisiType', array());

        return parent::getFisiType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvName($fisvName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvName', array($fisvName));

        return parent::setFisvName($fisvName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvName', array());

        return parent::getFisvName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvRealName($fisvRealName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvRealName', array($fisvRealName));

        return parent::setFisvRealName($fisvRealName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvRealName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvRealName', array());

        return parent::getFisvRealName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvMimetype($fisvMimetype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvMimetype', array($fisvMimetype));

        return parent::setFisvMimetype($fisvMimetype);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvMimetype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvMimetype', array());

        return parent::getFisvMimetype();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvExtension($fisvExtension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvExtension', array($fisvExtension));

        return parent::setFisvExtension($fisvExtension);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvExtension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvExtension', array());

        return parent::getFisvExtension();
    }

    /**
     * {@inheritDoc}
     */
    public function setFistDescription($fistDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFistDescription', array($fistDescription));

        return parent::setFistDescription($fistDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getFistDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFistDescription', array());

        return parent::getFistDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisdUploadDate($fisdUploadDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisdUploadDate', array($fisdUploadDate));

        return parent::setFisdUploadDate($fisdUploadDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisdUploadDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisdUploadDate', array());

        return parent::getFisdUploadDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvUploadIp($fisvUploadIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvUploadIp', array($fisvUploadIp));

        return parent::setFisvUploadIp($fisvUploadIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvUploadIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvUploadIp', array());

        return parent::getFisvUploadIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setFisvStatus($fisvStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFisvStatus', array($fisvStatus));

        return parent::setFisvStatus($fisvStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getFisvStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFisvStatus', array());

        return parent::getFisvStatus();
    }

}
