<div class="small-12 medium-8 large-7 columns">
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Últimos archivos subidos</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel">
                    <?php foreach($this->files as $file) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-1', 'row-2'))->next() ?>">
                        <div class="small-12 columns"><a href="<?php echo $this->url('view-file', array('folder'=>$file['fsciParentId'], 'filename'=>$file['fisvName'])); ?>"><?php echo $file['fscvRealName']; ?></a></div>
                        <div class="small-4 medium-3 large-3 columns text-small"><?php echo $file['fscdUploadDate']->format('d-m-Y'); ?></div>
                        <div class="small-8 medium-4 end large-3 columns text-small"><b>Descargas</b>: <?php echo $file['fsciTotalDownload']; ?></div>
                        <div class="small-12 medium-12 large-6 columns text-small"><b>Observación</b>:<?php echo $file['fsctDescription']; ?></div>
                    </div>
                    <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Archivos más descargados</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel">
                    <?php foreach($downloads as $file) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-1', 'row-2'))->next() ?>">
                        <div class="small-12 columns"><a href="<?php echo $this->url('view-file', array('folder'=>$file['fsciParentId'], 'filename'=>$file['fisvName'])); ?>"><?php echo $file['fscvRealName']; ?></a></div>
                        <div class="small-4 medium-3 large-3 columns text-small"><?php echo $file['fscdUploadDate']->format('d-m-Y'); ?></div>
                        <div class="small-8 medium-4 end large-3 columns text-small"><b>Descargas</b>: <?php echo $file['fsciTotalDownload']; ?></div>
                        <div class="small-12 medium-12 large-6 columns text-small"><b>Observación</b>: <?php echo $file['fsctDescription']; ?></div>
                    </div>
                    <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="small-12 medium-4 large-5 columns">
    <div class="row">
        <div class="large-11 columns">
            &nbsp;
        </div>
        <div class="large-offset-1 columns"></div>
    </div>
</div>
