<div class="row">
    <div class="small-12 medium-3 columns" id="login" style="border: 1px solid #000">
        <div class="row text-center">
            <h1>Cruz Verde</h1>
        </div>
        <form action="/dashboard" method="post">
            <div class="row collapse">
                <div class="row">
                    <div class="small-12 medium-12 columns">
                        <input type="text" name="username" placeholder="Username" />
                    </div>
                </div>
                <div class="row">
                    <div class="small-12 medium-12 columns">
                        <input type="password" name="password" placeholder="Password" />
                    </div>
                </div>
                <div class="row">
                    <div class="small-6 medium-6 small-centered medium-uncentered columns">
                        <button class="button radius tiny expand">Entrar</button>
                    </div>
                    <div class="small-6 medium-6 small-centered medium-uncentered columns inline">
                        <input id="rememberme" type="checkbox"><label for="rememberme">Recordarme</label>
                    </div>
                </div>
                <div class="row">
                    <div class="small-12 medium-12 small-centered medium-uncentered columns">
                        <a href="#">Olvidé la Contraseña</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>